### ISSUE TITLE
State changes don't work when inheriting from Blazor.Fluxor.Temporary.FluxorComponent

### ISSUE THREAD

**Issue by chanan** [mrpmorris/blazor-fluxor#27] opened 2018-06-02 00:31 UTC
Seems that something broke with Blazor.Fluxor.Temporary.FluxorComponent. State changes don't work - even calling StateHasChanged directly, although in the console I do see Index.StateHasChanged(). Removing the inherit tag and calling StateHasChanged() directly does work.

**Comment by mrpmorris** [comment] 2018-06-03 10:15
Can you provide a test case? It is working for me.

**Comment by mrpmorris** [comment] 2018-06-13 19:01
Are you still seeing this? If so then please send me a project that reproduces it.

**Comment by psampaio** [comment] 2018-06-13 21:44
I'm also seeing this behavior. I'll try to provide a sample, but maybe it's related to this commit?

https://github.com/aspnet/Blazor/commit/9933955bb2b6d19623aec4336189f7d7b6a18a74#diff-231f2ea84ed263076e2d32d1dd965be5

**Comment by mrpmorris** [comment] 2018-06-14 07:56
@psampaio What is your hypothesis regarding that commit?

**Comment by psampaio** [comment] 2018-06-14 08:33
My initial reasoning was that, given that the ContinueAfterLifecycleTask doesn't ConfigureAwait(false), the Rendered could be stuck while processing the render queue.

After sleeping  over it, if that was true it would have been a show stopper on Blazor itself, so it's not likely to be that commit.

**Comment by psampaio** [comment] 2018-06-14 22:46
I was able to track this issue down. It's not in Fluxor, but rather in Blazor itself. I'll report this there in the tomorrow, if I can.

The issue is related to triggering rendering (from statehaschanged) when you are doing an updatedisplay on the renderer. Those renderfragments are cleared before being applied and the component updates get stuck.

**Comment by psampaio** [comment] 2018-06-15 13:18
Replied there. You can probably close this one?

**Comment by mrpmorris** [comment] 2018-06-20 20:58
Could you test it in Fluxor 0.12.2? I saw this behaviour in 0.0.11 but have changed the code somewhat and now I am not seeing it.

**Closed** 2018-07-02 13:05 UTC
