### ISSUE TITLE
JSException: Could not find 'TryInitializeFluxor' in 'window'.

### ISSUE THREAD

**Issue by DNF-SaS** [mrpmorris/blazor-fluxor#103] opened 2019-12-03 15:03 UTC
Hi,

sometimes, I find the following error in the windows event log.
Why could this happen? (after restarting the iis apppool, it's most of the time good again=

Regards
Sascha

```
Application: w3wp.exe
CoreCLR Version: 4.700.19.47502
.NET Core Version: 3.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: Blazor.Fluxor.Exceptions.StoreInitializationException: Store initialization error
 ---> Microsoft.JSInterop.JSException: Could not find 'TryInitializeFluxor' in 'window'.
```

**Comment by mrpmorris** [comment] 2019-12-12 09:47
That is very odd. Blazor shouldn't initialize until after the scripts have been loaded.

Could you keep an eye on your browser's Network tab, and when it happens compare the time of the script download + the time of the error in the exception?

**Comment by mrpmorris** [comment] 2019-12-13 14:35
Closing this as a duplicate of #98 as the bug was related.

**Closed by mrpmorris** 2019-12-13 14:35 UTC
